# -*- coding: utf-8 -*-
"""social_codiing.ipyn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UIy0t2Whm1AqpXXf74xxeLt8_hG3k4_7

## **Activity 1:**

### **Building a Fibonacci Sequence Generator:**
"""

def generate_fibonacci_sequence(n):
  fibonacci_seq = [0, 1]

  while fibonacci_seq[-1] + fibonacci_seq[-2] <= n:
    next_num = fibonacci_seq[-1] + fibonacci_seq[-2]
    fibonacci_seq.append(next_num)

  return fibonacci_seq

try:
  n = int(input("Enter a number to generate Fibonacci Sequence upto that number: "))
  if n < 0:
    raise ValueError("Please enter a positive number.")

  fibonacci_sequence = generate_fibonacci_sequence(n)
  print("Fibonacci sequence upto", n, ":", fibonacci_sequence)

except ValueError as ve:
  print("Error: ", ve)
except Exception as e:
  print("An error occured: ", e)

"""## **Activity 2:**

### **Temperature Conversion:**
"""

def Farenhite_to_Celsius(f):
  return (f-32)* 5/9

def Celsius_to_Farenhite(c):
  return (c * 9/5) + 32

try:
  temp = int(input("Enter the temperature: "))
  scale = input("Enter the scale (C or F) : ").upper()

  if scale == 'C':
    f_temp = Celsius_to_Farenhite(temp)
    print(f"{temp:.2f}°C is equal to {f_temp:.2f}°F.")

  elif scale == 'F':
    c_temp = Farenhite_to_Celsius(temp)
    print(f"{temp:.2f}°F is equal to {c_temp:.2f}°C.")

except ValueError:
  print("Invalid input ! Please eneter a valid number.")